### ISSUE TITLE
Ruby shebang issues

### ISSUE THREAD

**Issue by peculiarism** [johnmccabe/vmpooler-bitbar#11]
I kept getting errors using the bitbar plugin with different gems not being installed, even though they were. Found out it was due to the ruby shebang, since I use rbenv the system version was different to the version I used in my own dev environment, and changing this to match the version specified in rbenv (using `#!/usr/bin/env /Users/Beth/.rbenv/shims/ruby`) caused the plugin to work again. Maybe add this to the README?

**Comment by johnmccabe** [comment]
Hi @eglenfield happy to merge a PR if you'd like to add this to the README 👍

**Comment by johnmccabe** [comment]
I've ported the plugin to Go so all the faffing about with Ruby is no longer an issue. Probably to be replaced by new even more confusing issues :)
