### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by asselvakumar** [johnmccabe/vmpooler-bitbar#18]
/Users/user/Documents/vmpooler-bitbar.30s
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/johnmccabe/vmpooler-bitbar/commands.errorMenu(0x14e6b00, 0xc42029e000)
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/commands/menu.go:237 +0x48c
github.com/johnmccabe/vmpooler-bitbar/commands.runMenu(0x1711bc0, 0x1737488, 0x0, 0x0)
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/commands/menu.go:49 +0x4519
github.com/johnmccabe/vmpooler-bitbar/commands.runRoot(0x1711bc0, 0x1737488, 0x0, 0x0)
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/commands/root.go:25 +0xba
github.com/johnmccabe/vmpooler-bitbar/vendor/github.com/spf13/cobra.(*Command).execute(0x1711bc0, 0xc4200101b0, 0x0, 0x0, 0x1711bc0, 0xc4200101b0)
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/johnmccabe/vmpooler-bitbar/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1711bc0, 0x1005f4c, 0xc42001c0b8, 0x0)
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/johnmccabe/vmpooler-bitbar/vendor/github.com/spf13/cobra.(*Command).Execute(0x1711bc0, 0x0, 0x13b07f5)
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/johnmccabe/vmpooler-bitbar/commands.Execute()
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/commands/root.go:11 +0x2d
main.main()
	/Users/john.mccabe/workspaces/go/src/github.com/johnmccabe/vmpooler-bitbar/main.go:6 +0x20

**Comment by dmcpl** [comment]
Hi,
This is happening because vmpooler is returning with a 503 Service Unavailable. I think vmpooler is down due to an expired certificate, and this is being fixed.

This plugin crashes because its expecting an error of at least 12 characters (not sure why, perhaps formatting) and it only gets a "503", I don't know if this is worth fixing as it should return to normal when vmpooler is fixed.

**Comment by johnmccabe** [comment]
I'm happy to accept a PR to handle this error scenario better.

**Comment by asselvakumar** [comment]
Thank you @dmcpl and @johnmccabe for your input. I can confirm it's working on my end now.
