### ISSUE TITLE
Getting error in vmfloaty version checking

### ISSUE THREAD

**Issue by dmcpl** [johnmccabe/vmpooler-bitbar#8]
Seem to be getting the getting the following error when running the script, removing the vmfloaty version checking code is a workaround:

```
vmpooler-bitbar.30s.rb:23:in `run': uninitialized constant VmpoolerBitbar::Version (NameError)
	from ./vmpooler-bitbar.30s.rb:360:in `<main>'
```

Quite possibly a setup issue on my end.

**Comment by willmeek** [comment]
Your PR fixes this. Had originally done the same locally and was about to push up, but the fix was exactly the same! :) 👍

**Comment by johnmccabe** [comment]
Closing as fix merged, thanks @dmcpl
